name: Hello World
# Controls when the workflow will run
on:
  push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps: # Ensure this is properly indented under 'build'
      - name: hello-job
        run: echo "Hello, world!"
